services:
  nodeodm:
    image: ${NODEODM_IMAGE:-opendronemap/nodeodm}
    container_name: 3d-survey-nodeodm
    ports:
      - "${NODEODM_PORT:-3002}:3000"
    volumes:
      - ./storage/nodeodm:/var/www/data
